BASEURL = "https://stats.quake.com"
APIEXT = "/api/v2/"

WEAPONS = [
    "UNKNOWN_DAMAGE_TYPE",
    "GAUNTLET",
    "MACHINEGUN",
    "MACHINEGUN_GRADE1",
    "SHOTGUN",
    "SHOTGUN_GRADE1",
    "NAILGUN",
    "NAILGUN_GRADE1",
    "ROCKET_LAUNCHER",
    "LIGHTNING_GUN",
    "RAILGUN",
    "LAGBOLT",
    ]

CHAMPIONS = [
    "NYX",
    "SCALEBEARER",
    "ANARKI",
    "SLASH",
    "CLUTCH",
    "GALENA",
    "RANGER",
    "VISOR",
    "SORLAG",
    "BJ_BLAZKOWICZ",
    "DOOM_SLAYER",
    "KEEL",
    "STROGG",
    "DEATH_KNIGHT",
    "ATHENA",
    "EISEN",
    ]

MAPS = [
    "AWOKEN",
    "BLOOD_RUN",
    "BLOOD_COVENANT",
    "BURIAL_CHAMBER",
    "CORRUPTED_KEEP",
    "FORTRESS_OF_THE_DEEP",
    ]

RANKS = [
    (2100, "Elite_01"),
    (2025, "Diamond_05"),
    (1950, "Diamond_04"),
    (1875, "Diamond_03"),
    (1800, "Diamond_02"),
    (1725, "Diamond_01"),
    (1650, "Gold_05"),
    (1575, "Gold_04"),
    (1500, "Gold_03"),
    (1425, "Gold_02"),
    (1350, "Gold_01"),
    (1275, "Silver_05"),
    (1200, "Silver_04"),
    (1125, "Silver_03"),
    (1050, "Silver_02"),
    (975, "Silver_01"),
    (900, "Bronze_05"),
    (825, "Bronze_04"),
    (750, "Bronze_03"),
    (675, "Bronze_02"),
    (0, "Bronze_01"),
]

HUMAN_RANKS = {
    "Elite_01": "Elite",
    "Diamond_05": "Diamond V",
    "Diamond_04": "Diamond IV",
    "Diamond_03": "Diamond III",
    "Diamond_02": "Diamond II",
    "Diamond_01": "Diamond I",
    "Gold_05": "Gold V",
    "Gold_04": "Gold IV",
    "Gold_03": "Gold III",
    "Gold_02": "Gold II",
    "Gold_01": "Gold I",
    "Silver_05": "Silver V",
    "Silver_04": "Silver IV",
    "Silver_03": "Silver III",
    "Silver_02": "Silver II",
    "Silver_01": "Silver I",
    "Bronze_05": "Bronze V",
    "Bronze_04": "Bronze IV",
    "Bronze_03": "Bronze III",
    "Bronze_02": "Bronze II",
    "Bronze_01": "Bronze I",
    "Zero_01": "Zero",
}
